export const prompts = [
  "Suggest a weekend trip itinerary near me for a quick and memorable getaway.",
  "Share effective packing hacks to make short trips convenient and stress-free.",
  "Provide tips for budget-friendly travel experiences without compromising on enjoyment.",
  "Explore lesser-known travel gems for unique and enriching experiences off the beaten path.",
  "What are the latest advancements and discoveries in the fascinating field of space exploration?",
  "Explain complex scientific concepts in a simple and understandable manner for broader comprehension.",
  "Recommend thought-provoking and educational science documentaries for an engaging learning experience.",
  "Share interesting and safe science experiments that can be easily conducted at home.",
  "Discuss how learning coding can benefit individuals with a passion for scientific exploration.",
  "Recommend efficient travel apps for seamless and enjoyable trip planning experiences.",
  "Provide safety advice for solo travelers exploring new destinations independently.",
  "Tips on discovering and savoring local cuisine for a more authentic travel experience.",
  "Describe a personal travel experience that left a lasting and positive impression on you.",
  "Recommend popular and scenic hiking trails located in or near my current geographical location.",
  "Overcoming jet lag: Tips to make the most of travel time and adjust quickly.",
  "Insights on capturing stunning and memorable travel photos using the capabilities of a smartphone.",
  "Explore interesting facts and insights into the captivating world of marine biology.",
  "Explain the concept of black holes in an easily understandable manner for a broad audience.",
  "Elaborate on the applications and significance of CRISPR technology in the field of genetics.",
  "Discuss the principles that allow airplanes to stay in the air during flight.",
  "Thoughts on the best books for science enthusiasts looking to expand their knowledge base.",
  "Ideal times to visit popular tourist destinations and make the most of the experience.",
  "Explore the benefits of practicing mindfulness during travel for a more enriching experience.",
  "How does the human brain process information, and what factors influence cognitive functions?",
  "Understanding dark matter and its crucial role in expanding our knowledge of the universe.",
  "Healthy and convenient snacks for road trips that are both tasty and energizing.",
  "Tips for identifying constellations in the night sky during outdoor adventures and stargazing.",
  "Quick and effective DIY workout routines suitable for travel and exploration activities.",
  "Impact of climate change on various travel destinations and how it shapes the travel experience.",
  "Role of vaccines and their mechanism in safeguarding human health against diseases.",
  "Practical tips for embracing sustainable and eco-friendly practices during travel and exploration.",
  "Latest innovations in renewable energy sources and their potential implications for the future.",
  "Recommend the best telescopes suitable for amateur astronomers exploring the wonders of the night sky.",
  "How do plants adapt to their environments, and what are some notable examples of adaptation?",
  "Exploration of the butterfly effect and its significance in chaos theory and complex systems.",
  "Tips for planning a budget-friendly and memorable road trip adventure for travel enthusiasts.",
  "Highlighting the contributions of famous women scientists and their impact across various scientific fields.",
  "Describe the process of photosynthesis and its crucial role in sustaining life on Earth.",
  "Tips for minimizing stress and making the most of experiences during holiday travel.",
  "Understanding the science behind various cooking techniques and their impact on food preparation.",
  "Advancements in artificial intelligence within the scientific field and their potential implications.",
  "Efficient tips for navigating public transportation in a new and unfamiliar city while traveling.",
  "Intriguing facts about the human body that surprise and captivate audiences interested in scientific exploration.",
  "Creative ways to engage with and learn from science in everyday life for curious minds.",
];
